#!/bin/sh

# Set these paths appropriately

BIN=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/bin
CMD=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/cmd
LIB=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
