#!/bin/sh

# Set these paths appropriately

BIN=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/bin
CMD=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/cmd
LIB=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
