#!/bin/sh

# Set these paths appropriately

BIN=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/bin
CMD=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/cmd
LIB=/Users/manishasharma/Desktop/temp-tagger/heideltime-standalone/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
